### ISSUE TITLE
struct abi not supported

### ISSUE THREAD

**Issue by wjmelements** [ethereum-lists/4bytes#37] opened 2020-07-03 09:11 UTC
The Airswap ABI uses the experimental struct abi. For example a struct with `uint256` and `bytes32` passed as an arg would result in a 4byte hash input like `swap((uint256,bytes32))` instead of `swap(uint256,bytes32)`.

**Comment by wjmelements** [comment] 2020-07-03 09:15
Structs are encoded as [tuples](https://solidity.readthedocs.io/en/v0.4.24/abi-spec.html).

**Comment by wjmelements** [comment] 2020-07-03 09:16
I only tested on 4bytes.directory; I have not tested the others.

**Comment by wjmelements** [comment] 2020-07-03 09:20
Concrete example: 0x67641c2f, used in https://etherscan.io/tx/0x6a527adb6a69d9b69a95fd79e8f7b31b7bb947d17c73e39e58c060e835303995 on https://etherscan.io/address/0x4572f2554421bd64bef1c22c8a81840e8d496bea#code, does not appear in the results of search even after submitting the signature.

**Comment by ligi** [comment] 2020-07-03 14:49
> I only tested on 4byte.directory; I have not tested the others.

This repo is the wrong one to report this issue and AFAIK it is a duplicate of:

https://github.com/pipermerriam/ethereum-function-signature-registry/issues/39

pinged @pipermerriam to merge the PR that should close the issue for the 4byte.directory

**Comment by pipermerriam** [comment] 2020-07-21 20:36
Almost done getting the hosting situation sorted out with the updated code that handles tuples:  You can see the staging environment here: http://app.4byte.directory/

**Comment by pipermerriam** [comment] 2020-07-21 22:34
This should now be working in production.

**Comment by ligi** [comment] 2020-07-22 13:15
I can confirm this working now:

![Selection_096](https://user-images.githubusercontent.com/111600/88180675-04d74480-cc2e-11ea-87d1-f5a265900d21.png)

so closing this issue.
@pipermerriam app.4byte.directory is down now as it seems. Maybe it makes sense to keep a staging environment like this up. Perhaps with a better name next time like staging.4byte.directory

**Closed by ligi** 2020-07-22 13:15 UTC
